Add missing newline in views.py for improved readability
 Run isort --check-only --profile black .
   ERROR: /home/runner/work/DjangoWithTest/DjangoWithTest/projects/pybo/views.py Imports are
   incorrectly sorted and/or formatted.
   Skipped 1 files
   Error: Process completed with exit code 1.

isort . --profile black